### ISSUE TITLE
Logos logs that it deleted or updated its own messages.

### ISSUE THREAD

**Issue by vxern** [vxern/logos#403]
![image](https://github.com/user-attachments/assets/5c9c4d37-27ba-4d4e-820c-0ae72ef03aa8)

**Comment by 2colours** [comment]
The scope of the task, unless otherwise stated:
"Logos should not log message deletes where it is its own message that is being deleted (...) same with updates".

**Comment by 2colours** [comment]
As of the writing of this comment, this is where related logic can be found: https://github.com/vxern/logos/blob/7c633fb27e501378150651efa103a09c90de2b35/source/library/stores/journalling.ts#L179

These methods mostly forward the calls to the particular logger that builds the required messages - however, since they already seem to do some validation beforehand, maybe they are the right place to catch and disregard cases where the bot interacts with its own messages.

I'll have to get a test environment but this seems to be a two-liner with the Discordeno API checked out.
